name: Build and Package Multiplatform Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-package:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc

          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin 

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu 


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev appstream

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.target }}

    - name: Rust Cache
      uses: swatinem/rust-cache@v2
      with:
        key: ${{ matrix.os }}-release-cache

    - name: Install cargo-packager
      shell: bash
      run: |
        cargo install cargo-packager --locked || true

    - name: Build binary in Release mode
      run: cargo build --release --target ${{ matrix.target }}

    - name: Package Application
      run: cargo packager --release --formats all

    - name: Upload Artifacts to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/${{ matrix.target }}/release/plg
          target/${{ matrix.target }}/release/plg.exe
          dist/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
